#!/bin/bash

echo "Started build..."
DIR="`pwd`"
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$DIR

# build backend
go fmt ./...
go build -ldflags "-s -w" src/main/main.go
mkdir -p release/v$1
mv main release/v$1/acweb

# build client
cd public
node-sass --output css scss/main.scss
./minvue -config=minify.json
cd ..

# copy additional folders
cp tracks.json release/v$1/tracks.json
cp cars.json release/v$1/cars.json
cp -r db release/v$1/db
cp README.md release/v$1/README.md
cp LICENSE release/v$1/LICENSE
cp CHANGELOG.md release/v$1/CHANGELOG.md
cp -a public release/v$1/public

# remove stuff
rm -r release/v$1/public/app
rm -r release/v$1/public/scss
rm -r release/v$1/public/template
rm release/v$1/public/build_app
rm release/v$1/public/build_sass
rm release/v$1/public/minify.json
rm release/v$1/public/minvue

echo "done"
