#!/bin/bash

echo "Started build..."
DIR="`pwd`"
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$DIR

go get github.com/DeKugelschieber/go-session
go get github.com/DeKugelschieber/go-util
go get github.com/go-sql-driver/mysql

# build backend
go fmt ./...
go build -ldflags "-s -w" src/main/main.go
mkdir -p release/v$1
mv main release/v$1/acweb

# build client
cd public
node-sass --output css scss/main.scss
./minvue -config=minify.json
cd ..

# copy additional folders
cp config.original.json release/v$1/config.json
cp -r db release/v$1/db
cp README.md release/v$1/README.md
cp LICENSE release/v$1/LICENSE
cp CHANGELOG.md release/v$1/CHANGELOG.md
cp -a public release/v$1/public

# remove stuff
rm -r release/v$1/public/app
rm -r release/v$1/public/scss
rm -r release/v$1/public/template
rm release/v$1/public/build_app
rm release/v$1/public/build_sass
rm release/v$1/public/minify.json
rm release/v$1/public/minvue
#rm release/v$1/public/js/vue.js
#rm release/v$1/public/js/vue-router.js
#rm release/v$1/public/js/vue-resource.js

echo "done"
