#!/bin/bash

echo "Starting application..."
DIR="`pwd`"
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$DIR

export ACWEB_HOST=localhost:8080
export ACWEB_LOGDIR=
export ACWEB_TLS_PRIVATE_KEY=
export ACWEB_TLS_CERT=
export ACWEB_DB_USER=root
export ACWEB_DB_PASSWORD=
export ACWEB_DB_HOST=
export ACWEB_DB=acweb

go get github.com/DeKugelschieber/go-session
go get github.com/DeKugelschieber/go-util
go get github.com/DeKugelschieber/go-resp
go get github.com/go-sql-driver/mysql

go run src/main/main.go
