#!/bin/bash

echo "Started build..."

cd ..

# build backend
go fmt ./...
go build -ldflags "-s -w" main.go
mkdir -p release/v$1
mv main release/v$1/acweb

# build client
# TODO switch to npm
cd public
node-sass --output css scss/main.scss
./minvue -config=minify.json
cd ..

# copy additional folders
cp -r config release/v$1/config
cp -r schema release/v$1/schema
cp README.md release/v$1/README.md
cp LICENSE release/v$1/LICENSE
cp CHANGELOG.md release/v$1/CHANGELOG.md
cp -a public release/v$1/public

# remove stuff
rm -r release/v$1/public/app
rm -r release/v$1/public/scss
rm -r release/v$1/public/template
rm release/v$1/public/build_app
rm release/v$1/public/build_sass
rm release/v$1/public/minify.json
rm release/v$1/public/minvue

echo "done"
